on: [push, workflow_dispatch]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Hello world action step
        id: hello
        uses: Jamalam360/test-action@v1